;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        keyboard-quit
        paredit-forward-kill-word
        paredit-raise-sexp
        paredit-semicolon
        transpose-sexps
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-mc/mc/mark-next-like-this
        smex
        w32-drag-n-drop
        ))
