;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-change
        evil-insert
        evil-normal-state
        hydra-mc/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-like-this
        keyboard-quit
        multiple-cursors-hydra/mc/unmark-previous-like-this
        paredit-forward-kill-word
        paredit-raise-sexp
        paredit-semicolon
        transpose-sexps
        ))

(setq mc/cmds-to-run-once
      '(
        evil-indent-i-indent
        evil-inner-tag
        evil-next-visual-line
        hydra-mc-okke/mc/mark-next-like-this
        hydra-multiple-cursors-hydra/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        mc-hydra/mc/mark-next-like-this
        multiple-cursors-hydra/mc/mark-next-like-this
        multiple-cursors-hydra/mc/mark-previous-like-this
        multiple-cursors-hydra/mc/skip-to-next-like-this
        okke-hydra-mc/mc/mark-next-like-this
        smex
        ))
